/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface HomeContent {
        "content": any;
    }
    interface PageContent {
        "content": any;
    }
    interface PageTemplate {
        "slug": any;
    }
    interface SiteClients {
        "clients": any;
    }
    interface SiteFooter {
    }
    interface SiteHead {
        "meta": any;
    }
    interface SiteNav {
        "hero": any;
    }
    interface SiteServices {
        "services": any;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLHomeContentElement extends Components.HomeContent, HTMLStencilElement {
    }
    var HTMLHomeContentElement: {
        prototype: HTMLHomeContentElement;
        new (): HTMLHomeContentElement;
    };
    interface HTMLPageContentElement extends Components.PageContent, HTMLStencilElement {
    }
    var HTMLPageContentElement: {
        prototype: HTMLPageContentElement;
        new (): HTMLPageContentElement;
    };
    interface HTMLPageTemplateElement extends Components.PageTemplate, HTMLStencilElement {
    }
    var HTMLPageTemplateElement: {
        prototype: HTMLPageTemplateElement;
        new (): HTMLPageTemplateElement;
    };
    interface HTMLSiteClientsElement extends Components.SiteClients, HTMLStencilElement {
    }
    var HTMLSiteClientsElement: {
        prototype: HTMLSiteClientsElement;
        new (): HTMLSiteClientsElement;
    };
    interface HTMLSiteFooterElement extends Components.SiteFooter, HTMLStencilElement {
    }
    var HTMLSiteFooterElement: {
        prototype: HTMLSiteFooterElement;
        new (): HTMLSiteFooterElement;
    };
    interface HTMLSiteHeadElement extends Components.SiteHead, HTMLStencilElement {
    }
    var HTMLSiteHeadElement: {
        prototype: HTMLSiteHeadElement;
        new (): HTMLSiteHeadElement;
    };
    interface HTMLSiteNavElement extends Components.SiteNav, HTMLStencilElement {
    }
    var HTMLSiteNavElement: {
        prototype: HTMLSiteNavElement;
        new (): HTMLSiteNavElement;
    };
    interface HTMLSiteServicesElement extends Components.SiteServices, HTMLStencilElement {
    }
    var HTMLSiteServicesElement: {
        prototype: HTMLSiteServicesElement;
        new (): HTMLSiteServicesElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "home-content": HTMLHomeContentElement;
        "page-content": HTMLPageContentElement;
        "page-template": HTMLPageTemplateElement;
        "site-clients": HTMLSiteClientsElement;
        "site-footer": HTMLSiteFooterElement;
        "site-head": HTMLSiteHeadElement;
        "site-nav": HTMLSiteNavElement;
        "site-services": HTMLSiteServicesElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface HomeContent {
        "content"?: any;
    }
    interface PageContent {
        "content"?: any;
    }
    interface PageTemplate {
        "slug"?: any;
    }
    interface SiteClients {
        "clients"?: any;
    }
    interface SiteFooter {
    }
    interface SiteHead {
        "meta"?: any;
    }
    interface SiteNav {
        "hero"?: any;
    }
    interface SiteServices {
        "services"?: any;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "home-content": HomeContent;
        "page-content": PageContent;
        "page-template": PageTemplate;
        "site-clients": SiteClients;
        "site-footer": SiteFooter;
        "site-head": SiteHead;
        "site-nav": SiteNav;
        "site-services": SiteServices;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "home-content": LocalJSX.HomeContent & JSXBase.HTMLAttributes<HTMLHomeContentElement>;
            "page-content": LocalJSX.PageContent & JSXBase.HTMLAttributes<HTMLPageContentElement>;
            "page-template": LocalJSX.PageTemplate & JSXBase.HTMLAttributes<HTMLPageTemplateElement>;
            "site-clients": LocalJSX.SiteClients & JSXBase.HTMLAttributes<HTMLSiteClientsElement>;
            "site-footer": LocalJSX.SiteFooter & JSXBase.HTMLAttributes<HTMLSiteFooterElement>;
            "site-head": LocalJSX.SiteHead & JSXBase.HTMLAttributes<HTMLSiteHeadElement>;
            "site-nav": LocalJSX.SiteNav & JSXBase.HTMLAttributes<HTMLSiteNavElement>;
            "site-services": LocalJSX.SiteServices & JSXBase.HTMLAttributes<HTMLSiteServicesElement>;
        }
    }
}
