/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface PageHome {
    }
    interface SiteContent {
    }
    interface SiteNav {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLSiteContentElement extends Components.SiteContent, HTMLStencilElement {
    }
    var HTMLSiteContentElement: {
        prototype: HTMLSiteContentElement;
        new (): HTMLSiteContentElement;
    };
    interface HTMLSiteNavElement extends Components.SiteNav, HTMLStencilElement {
    }
    var HTMLSiteNavElement: {
        prototype: HTMLSiteNavElement;
        new (): HTMLSiteNavElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "page-home": HTMLPageHomeElement;
        "site-content": HTMLSiteContentElement;
        "site-nav": HTMLSiteNavElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface PageHome {
    }
    interface SiteContent {
    }
    interface SiteNav {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "page-home": PageHome;
        "site-content": SiteContent;
        "site-nav": SiteNav;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "site-content": LocalJSX.SiteContent & JSXBase.HTMLAttributes<HTMLSiteContentElement>;
            "site-nav": LocalJSX.SiteNav & JSXBase.HTMLAttributes<HTMLSiteNavElement>;
        }
    }
}
